version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    platform: linux/amd64
    container_name: rabbitmq-hospital
    ports:
      - "5672:5672"   # Porta de comunicação da aplicação
      - "15672:15672" # Porta do painel de controle (Management)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest