server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_db
    username: postgres
    password: sua_senha_aqui
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest